// Database'e yeni bir post islemi gerceklestirmek icin olusturuldu. Böylece database'e buradan post islemi yapabiliriz.
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Deneme deneme deneme",
    "important":true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Deneme 123",
    "important":true
}
###
POST  http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Deneme Post Postman",
    "important":true
}